### ISSUE TITLE
Impossible to compile software

### ISSUE THREAD

**Issue by kRustybasti** [Rocket-Search/sap-mon#1]
Hello,

I am trying to compile the source code from the github clone.
I edited the Makefile and added the compiler line -std=c++11 however the compilation explodes because it asks me for a directory that doesn't exist.

xml_extract.cpp:33:41: fatal error: boost/property_tree/ptree.hpp: No such file or directory

I thank you for this project!

**Comment by Rocket-Search** [comment]
Hello,

do you have "Boost C++ Libraries" https://www.boost.org/ installed ?
If yes, please do a search for ptree.hpp (command: find / -iname ptree.hpp) on OS level and manual 
change the directory for ptree.hpp in xml_extract.cpp .

best regards
T. Reineck
